[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1", branch = "v2.0.0" }
alloy-sol-types = { workspace = true }
fibonacci-lib = { path = "../lib" }
